name: vsc_image_editor_example
description: An example using vsc_image_editor.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vsc_image_editor:
    path: ../
  image: ^3.2.0
  share_plus: ^4.5.2
  cross_file: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
