name: vsc_image_editor_example
description: An example using vsc_image_editor.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vsc_image_editor:
    path: ../
  image: ^4.0.17
  share_plus: ^7.0.2
  cross_file: ^0.3.3+4
  file_saver: ^0.2.4
#  file_saver: # ^0.1.0 - broke with flutter 3
#    git:
#      url: https://github.com/incrediblezayed/file_saver.git
#      ref: 877b25c6088491037be79e426a7c9c1598d17142
  path_provider: ^2.0.11
  path: ^1.8.3
  file_picker: ^5.3.2
  chunked_stream: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
#  assets:
#    - assets
