name: vsc_image_editor
description: A pure-Dart image editor for Flutter.
version: 0.0.1
homepage: https://vscorp.com
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+4
  mobx: ^2.2.0
  zoom_widget: ^2.0.1
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  mobx_codegen: ^2.3.0

flutter:
