name: vsc_image_editor
description: A pure-Dart image editor for Flutter.
version: 0.0.1
homepage: https://vscorp.com
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+4
  mobx: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7

flutter:
